# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('img', models.CharField(default='axf.png', max_length=40)),
            ],
        ),
    ]
